# backend/Dockerfile.dev
FROM golang:1.23-alpine

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code  
COPY . .

# Expose port
EXPOSE 8080

# Simple go run command
CMD ["go", "run", "./cmd/api"]